language: scala

branches:
  only:
    - master
    - 2.12.x
    - 2.11.x
    - 2.10.x
    - 2.9.x
    - 2.8.x

scala:
  - "2.12.0-M3"

jdk:
  - oraclejdk8

sudo: false

notifications:
  email:
    recipients:
      - marko@mentat-labs.com

script:
  # Try to build documentation, package sources, run ProGuard and test
  - sbt ++$TRAVIS_SCALA_VERSION publishLocal proguard:proguard clean test

# after_success:
#   - pip install --user codecov && codecov
