language: scala

scala:
  - "2.11.7"

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

sudo: false

notifications:
  email:
    recipients:
      - marko@mentat-labs.com

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test publishLocal

after_success:
  - pip install --user codecov && codecov
