language: scala

scala:
  - "2.8.1"
  - "2.8.2"

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

sudo: false

notifications:
  email:
    recipients:
      - marko@mentat-labs.com

script: sbt ++$TRAVIS_SCALA_VERSION compile
