language: scala

branches:
  only:
    - 2.12.x
    - 2.11.x
    - 2.10.x
    - 2.9.x
    - 2.8.x

scala:
  - "2.8.1"
  - "2.8.2"

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

sudo: false

notifications:
  email:
    recipients:
      - marko@mentat-labs.com

script: sbt ++$TRAVIS_SCALA_VERSION publishLocal
